name: wexploria_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  shimmer: ^3.0.0
  
  # Backend & Auth
  supabase_flutter: ^2.6.0
  sign_in_with_apple: ^6.1.2
  google_sign_in: ^6.2.1
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Payments
  flutter_stripe: ^11.1.0
  
  # Maps
  mapbox_maps_flutter: ^2.3.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  
  # Storage & Cache
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Notifications
  onesignal_flutter: ^5.2.7
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0
  
  # Navigation
  go_router: ^14.6.2
  
  # Animations
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wexploria_logo.png
    - assets/images/wexploria_logo2.png
    - assets/images/wexploria_logo3.png
    - assets/images/homme-chevauchant-sa-planche-de-surf-et-s-amuser.jpg
    - assets/images/parapente-tandem-survolant-le-bord-de-mer-avec-de-l-eau-bleue-et-du-ciel-sur-horison-vue-de-parapente-et-blue-lagoon-en-turquie.jpg
    - assets/images/marhba.jpg
    - assets/images/welcome1.jpg
    - assets/images/welcome2.jpg
    - assets/images/welcome3.jpg